---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vcverifier-cm
data:
  server.yaml: |
    server:
      port: 7070
    verifier: 
        tirAddress: http://satellite:6060/trusted_issuer/v3/issuers/
        did: did:key:z6MksU6tMfbaDzvaRe5oFE4eZTVTV4HJM4fmQWWGsDGQVsEr
    ssiKit:
        auditorURL: http://waltid:7003
    logging:
      level: DEBUG
      jsonLogging: true
      logRequests: true
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: vcverifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcverifier
  template:
    metadata:
      labels:
        app: vcverifier
      annotations:
        deployment/id: "_DEFAULT_DEPLOYMENT_"
    spec:
      containers:
        - name: vcverifier
          image: vc-verifier
          imagePullPolicy: Never
          ports:
            - containerPort: 7070
              name: api
          env:
            - name: CONFIG_FILE
              value: /configs/server.yaml
          volumeMounts:
            - mountPath: /configs/
              name: config-volume
      volumes:
        - name: config-volume
          configMap:
            name: vcverifier-cm
---
kind: Service
apiVersion: v1
metadata:
  name: vcverifier
spec:
  type: LoadBalancer
  ports:
    - name: api
      port: 7070
      targetPort: api
      protocol: TCP
  selector:
    app: vcverifier